services:
  - type: web
    name: rada-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MINMO_API_KEY
        sync: false
      - key: MINMO_WEBHOOK_SECRET
        sync: false
      - key: TELEGRAM_WEBHOOK_URL
        sync: false
